set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[]}]

set_property PACKAGE_PIN V17 [get_ports {sw[7]}]
set_property PACKAGE_PIN V16 [get_ports {sw[6]}]
set_property PACKAGE_PIN W16 [get_ports {sw[5]}]
set_property PACKAGE_PIN W17 [get_ports {sw[4]}]
set_property PACKAGE_PIN W15 [get_ports {sw[3]}]
set_property PACKAGE_PIN V15 [get_ports {sw[2]}]
set_property PACKAGE_PIN W14 [get_ports {sw[1]}]
set_property PACKAGE_PIN W13 [get_ports {sw[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports oled_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports oled_res_n]
set_property IOSTANDARD LVCMOS33 [get_ports oled_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports oled_dc]
set_property IOSTANDARD LVCMOS33 [get_ports oled_cs_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100mhz]
set_property PACKAGE_PIN W5 [get_ports clk_100mhz]
set_property PACKAGE_PIN A14 [get_ports oled_cs_n]
set_property PACKAGE_PIN A15 [get_ports oled_dc]
set_property PACKAGE_PIN A16 [get_ports oled_mosi]
set_property PACKAGE_PIN A17 [get_ports oled_res_n]
set_property PACKAGE_PIN B16 [get_ports oled_sclk]

