set_property PACKAGE_PIN A17 [get_ports spi_clk]
set_property PACKAGE_PIN A18 [get_ports spi_mosi]
set_property PACKAGE_PIN B17 [get_ports spi_cs]
set_property PACKAGE_PIN B18 [get_ports oled_dc]
set_property PACKAGE_PIN C17 [get_ports oled_res]
set_property IOSTANDARD LVCMOS33 [get_ports spi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports spi_cs]
set_property IOSTANDARD LVCMOS33 [get_ports oled_dc]
set_property IOSTANDARD LVCMOS33 [get_ports oled_res]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN U14 [get_ports rst]
set_property PACKAGE_PIN M18 [get_ports clk]
